export const PRINTA_APP_KEY = {
  TOKEN: "printa_auth_session",
  REFRESH: "printa_refresh_session",
  USER: "printa_user_session",
};

export const orders = [
  {
    id: "ORD-1284",
    date: "2025-09-30",
    customer: "John Smith",
    product: "Custom T-Shirt",
    quantity: 50,
    hub: "NYC Hub",
    status: "In Progress",
  },
  {
    id: "ORD-1283",
    date: "2025-09-30",
    customer: "Sarah Johnson",
    product: "Tote Bag",
    quantity: 100,
    hub: "LA Hub",
    status: "Shipped",
  },
  {
    id: "ORD-1282",
    date: "2025-09-29",
    customer: "Mike Davis",
    product: "Poster",
    quantity: 25,
    hub: "Chicago Hub",
    status: "Completed",
  },
  {
    id: "ORD-1281",
    date: "2025-09-29",
    customer: "Emily Brown",
    product: "Mug",
    quantity: 75,
    hub: "Unassigned",
    status: "Received",
  },
  {
    id: "ORD-1280",
    date: "2025-09-28",
    customer: "David Wilson",
    product: "Hoodie",
    quantity: 30,
    hub: "NYC Hub",
    status: "In Progress",
  },
];

// Mock data
export const printHubs = [
  {
    id: "hub-1",
    name: "NYC Hub",
    location: "New York, NY",
    address: "456 Print Ave, New York, NY 10001",
    status: "Operational",
    activeOrders: 12,
    completedToday: 8,
    capacity: 85,
    avgProcessingTime: "2.3 hours",
    contact: {
      manager: "Jane Cooper",
      email: "jane.cooper@printhub.com",
      phone: "+1 (555) 987-6543",
    },
  },
  {
    id: "hub-2",
    name: "LA Hub",
    location: "Los Angeles, CA",
    address: "789 Design Blvd, Los Angeles, CA 90001",
    status: "Operational",
    activeOrders: 8,
    completedToday: 12,
    capacity: 65,
    avgProcessingTime: "1.8 hours",
    contact: {
      manager: "Jane Cooper",
      email: "jane.cooper@printhub.com",
      phone: "+1 (555) 987-6543",
    },
  },
  {
    id: "hub-3",
    name: "Chicago Hub",
    location: "Chicago, IL",
    address: "321 Print St, Chicago, IL 60601",
    status: "Operational",
    activeOrders: 15,
    completedToday: 6,
    capacity: 92,
    avgProcessingTime: "2.1 hours",
    contact: {
      manager: "Jane Cooper",
      email: "jane.cooper@printhub.com",
      phone: "+1 (555) 987-6543",
    },
  },
  {
    id: "hub-4",
    name: "Miami Hub",
    location: "Miami, FL",
    address: "654 Creative Way, Miami, FL 33101",
    status: "Maintenance",
    activeOrders: 0,
    completedToday: 0,
    capacity: 0,
    avgProcessingTime: "N/A",
    contact: {
      manager: "Jane Cooper",
      email: "jane.cooper@printhub.com",
      phone: "+1 (555) 987-6543",
    },
  },
];

export const productCategories = [
  {
    id: "1",
    name: "Apparel",
    description: "Clothing and wearable items",
    productCount: 45,
    expanded: false,
    subCategories: [
      {
        id: "1-1",
        name: "T-Shirts",
        description: "Custom printed t-shirts",
        productCount: 20,
      },
      {
        id: "1-2",
        name: "Hoodies",
        description: "Comfortable hoodies",
        productCount: 15,
      },
      {
        id: "1-3",
        name: "Tank Tops",
        description: "Sleeveless shirts",
        productCount: 10,
      },
    ],
  },
  {
    id: "2",
    name: "Accessories",
    description: "Fashion accessories and add-ons",
    productCount: 32,
    expanded: false,
    subCategories: [
      {
        id: "2-1",
        name: "Tote Bags",
        description: "Reusable shopping bags",
        productCount: 18,
      },
      {
        id: "2-2",
        name: "Hats",
        description: "Caps and beanies",
        productCount: 14,
      },
    ],
  },
  {
    id: "3",
    name: "Print",
    description: "Printed materials and artwork",
    productCount: 28,
    expanded: false,
    subCategories: [
      {
        id: "3-1",
        name: "Posters",
        description: "Wall art posters",
        productCount: 15,
      },
      {
        id: "3-2",
        name: "Canvas Prints",
        description: "Canvas wall art",
        productCount: 13,
      },
    ],
  },
  {
    id: "4",
    name: "Drinkware",
    description: "Mugs, bottles, and cups",
    productCount: 22,
    expanded: false,
    subCategories: [
      {
        id: "4-1",
        name: "Mugs",
        description: "Ceramic coffee mugs",
        productCount: 12,
      },
      {
        id: "4-2",
        name: "Water Bottles",
        description: "Reusable bottles",
        productCount: 10,
      },
    ],
  },
];

export const specificationTypes = [
  { value: "sizeOptions", label: "Size Options" },
  { value: "shapeOptions", label: "Shape Options" },
  { value: "sideOptions", label: "Side Options" },
  { value: "coverOptions", label: "Cover Options" },
  { value: "bindingOptions", label: "Binding Options" },
  { value: "paperOptions", label: "Paper Options" },
  { value: "pageOptions", label: "Page Options" },
  { value: "orientationOptions", label: "Orientation Options" },
  { value: "thicknessOptions", label: "Thickness/Material Options" },
  { value: "finishOptions", label: "Finish/Quality Options" },
  { value: "cornersOptions", label: "Corners Options" },
  { value: "paperStockOptions", label: "Paper Stock Options" },
  { value: "fillerPaperOptions", label: "Filler Paper Options" },
];
