import ThemeQueryProvider from "@/provider";
import type { Metadata } from "next";
import { Manrope, Work_Sans } from "next/font/google";
import "./globals.css";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const workSansHeading = Work_Sans({
  variable: "--font-work-heading",
  subsets: ["latin"],
  weight: ["600"],
});

const manropeHeading = Manrope({
  variable: "--font-manrope-heading",
  subsets: ["latin"],
  weight: ["600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${workSansHeading.variable} ${manropeHeading.variable} antialiased`}
      >
        <ThemeQueryProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeQueryProvider>
      </body>
    </html>
  );
}
